version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly, day: monday }
    groups:
      minor-e-patch:
        update-types: [minor, patch]
    labels: [chore, dependencies]
    commit-message: { prefix: chore }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    labels: [ci, dependencies]
    commit-message: { prefix: ci }
  - package-ecosystem: docker
    directory: /infra/docker
    schedule: { interval: weekly }
    labels: [build, dependencies]
    commit-message: { prefix: build }
