#!/usr/bin/env bash
# Scaffold idempotente do iam-platform — recria a árvore de diretórios.
# Os arquivos de conteúdo vivem no repositório; este script garante apenas a estrutura.
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p .claude
mkdir -p .claude/agents
mkdir -p .claude/commands
mkdir -p .husky
mkdir -p docs
mkdir -p docs/api
mkdir -p docs/architecture
mkdir -p docs/database
mkdir -p docs/decisions
mkdir -p docs/deployment
mkdir -p docs/images
mkdir -p docs/observability
mkdir -p docs/security
mkdir -p infra
mkdir -p infra/backup
mkdir -p infra/compose
mkdir -p infra/docker
mkdir -p infra/grafana
mkdir -p infra/grafana/provisioning
mkdir -p infra/grafana/provisioning/dashboards
mkdir -p infra/grafana/provisioning/datasources
mkdir -p infra/loki
mkdir -p infra/mongodb
mkdir -p infra/otel
mkdir -p infra/postgres
mkdir -p infra/prometheus
mkdir -p infra/scripts
mkdir -p infra/scripts/github-rulesets
mkdir -p infra/tempo
mkdir -p monitoring
mkdir -p monitoring/alerts
mkdir -p monitoring/dashboards
mkdir -p monitoring/recording-rules
mkdir -p openapi
mkdir -p openapi/examples
mkdir -p openapi/postman
mkdir -p openapi/schemas
mkdir -p scripts
mkdir -p security
mkdir -p security/cosign
mkdir -p security/policies
mkdir -p security/sbom
mkdir -p security/threat-model
mkdir -p security/trivy
mkdir -p specs
mkdir -p specs/001-authentication
mkdir -p specs/002-user-management
mkdir -p specs/003-rbac
mkdir -p specs/004-abac
mkdir -p specs/005-refresh-token
mkdir -p specs/006-session-management
mkdir -p specs/007-jwks
mkdir -p specs/008-key-rotation
mkdir -p specs/009-password-management
mkdir -p specs/010-mfa
mkdir -p specs/011-api-clients
mkdir -p specs/012-oauth2
mkdir -p specs/013-audit
mkdir -p specs/014-security-events
mkdir -p specs/015-observability
mkdir -p specs/016-rate-limiting
mkdir -p specs/017-health
mkdir -p specs/018-admin-panel-api
mkdir -p specs/019-notifications
mkdir -p specs/020-backup-recovery
mkdir -p specs/021-deployment
mkdir -p specs/022-monitoring
mkdir -p specs/023-ci-cd
mkdir -p specs/024-security-hardening
mkdir -p specs/_template
mkdir -p src
mkdir -p src/bootstrap
mkdir -p src/config
mkdir -p src/database
mkdir -p src/database/migrations
mkdir -p src/database/mongodb
mkdir -p src/database/mongodb/collections
mkdir -p src/database/postgres
mkdir -p src/database/postgres/queries
mkdir -p src/database/repositories
mkdir -p src/database/seeds
mkdir -p src/modules
mkdir -p src/modules/audit
mkdir -p src/modules/auth
mkdir -p src/modules/health
mkdir -p src/modules/jwks
mkdir -p src/modules/metrics
mkdir -p src/modules/permissions
mkdir -p src/modules/refresh-token
mkdir -p src/modules/roles
mkdir -p src/modules/sessions
mkdir -p src/modules/users
mkdir -p src/plugins
mkdir -p src/shared
mkdir -p src/shared/cache
mkdir -p src/shared/constants
mkdir -p src/shared/crypto
mkdir -p src/shared/errors
mkdir -p src/shared/jwt
mkdir -p src/shared/logger
mkdir -p src/shared/middleware
mkdir -p src/shared/types
mkdir -p src/shared/utils
mkdir -p src/shared/validators
mkdir -p tests
mkdir -p tests/contract
mkdir -p tests/e2e
mkdir -p tests/fixtures
mkdir -p tests/integration
mkdir -p tests/mocks
mkdir -p tests/mutation
mkdir -p tests/performance
mkdir -p tests/performance/k6
mkdir -p tests/unit
echo "Estrutura garantida."
