name: iam-monitoring
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.131.0
    command: ["--config=/etc/otel/config.yaml"]
    volumes: ["../otel/config.yaml:/etc/otel/config.yaml:ro"]
    ports: ["4317:4317", "4318:4318"]

  prometheus:
    image:  prom/prometheus:v3.6.0
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../../monitoring/alerts:/etc/prometheus/alerts:ro
    ports: ["9090:9090"]

  loki:
    image: grafana/loki:3.5.3
    ports: ["3100:3100"]

  tempo:
    image: grafana/tempo:2.8.2
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes: ["../tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro"]
    ports: ["3200:3200"]

  grafana:
    image: grafana/grafana:13.0.3
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning:ro
      - ../../monitoring/dashboards:/var/lib/grafana/dashboards:ro
    ports: ["3001:3000"]
    depends_on: [prometheus, loki, tempo]
